### ISSUE TITLE
Seeking doesn't work on Tizen OS

### ISSUE THREAD

**Issue by bytecraft32** [detarkende/stremio-ncore-addon#53]
On Tizen OS (Samsung Smart TV), seeking functionality doesn't work. I suspect the device expects specific HTTP headers or response formats for seeking support. The same functionality works correctly on WebOS, Stremio local Linux app, and Android devices.

I tested across multiple versions (0.8.0, 0.8.0-pre-release-2, 0.7.0, 0.6.0). 
Seeking works correctly with the Torrentio and Piratebay+ add-ons, which may be useful information when diagnosing this issue.

**Comment by detarkende** [comment]
Hi @bytecraft32 

Have you tried different torrents? 

I also have a Samsung Tizen OS Tv and seeking seems to work for me. Maybe it's specific to a torrent?

**Comment by markflaisz** [comment]
It didn’t work for me either, so I bought an Android TV box. Until the latest update (Tizen OS update in early March), it crashed every time I tried to start a video. Now it plays the video, but seeking doesn’t work. I thought this was a bug with the TV.

**Comment by bytecraft32** [comment]
At the moment, I'm investigating further to pinpoint the issue. It's possible I've misconfigured something.

I discovered that when using cloudflared, the seeking functionality works correctly on both my Tizen OS monitor and Tizen OS TV. However, when the setup is configured to be accessible only on the local network, the previously mentioned seeking issue occurs.

https://192-168-0-80.local-ip.medicmobile.org:3443/settings
 * Only accessible on local network 
Local network IP: 192.168.0.80

casaOs compose file:
```
name: stremio-ncore-addon
services:
  stremio-ncore-addon:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 7334M
    environment:
      - NCORE_PASSWORD=---------------------
      - NCORE_USERNAME=---------------------
    image: detarkende/stremio-ncore-addon:0.8.0
    labels:
      icon: https://github.com/detarkende/stremio-ncore-addon/blob/master/client/public/stremio-ncore-addon-logo-rounded.png?raw=true
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 3443
        published: "3443"
        protocol: tcp
      - target: 42069
        published: "42069"
        protocol: ""
      - target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/server/Stremio
        target: /addon
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: 192-168-0-80.local-ip.medicmobile.org
  icon: https://github.com/detarkende/stremio-ncore-addon/blob/master/client/public/stremio-ncore-addon-logo-rounded.png?raw=true
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: stremio-ncore-addon
  title:
    custom: Stremio nCore addon
```

**Comment by detarkende** [comment]
Thanks @bytecraft32 for the info. I will try it with the local addon on Tizen.

**Comment by hewdrey** [comment]
I see an error message, maybe this could help. I see that no torrents are shown in Torrents page, maybe torrent server is down?

TypeError: fetch failed
ncore      |     at node:internal/deps/undici/undici:13178:13
ncore      |     at async TorrentServerSdk.getTorrent (file:///app/dist/server/services/torrent-store/torrent-server.sdk.js:10:21)
ncore      |     at async TorrentStoreService.getTorrent (file:///app/dist/server/services/torrent-store/torrent-store.service.js:58:25)
ncore      |     at async StreamController.play (file:///app/dist/server/controllers/stream.controller.js:83:23)
ncore      |     at async dispatch (file:///app/node_modules/.pnpm/hono@4.7.2/node_modules/hono/dist/compose.js:22:17)
ncore      |     at async dispatch (file:///app/node_modules/.pnpm/hono@4.7.2/node_modules/hono/dist/compose.js:22:17)
ncore      |     at async file:///app/dist/server/index.js:93:18
ncore      |     at async dispatch (file:///app/node_modules/.pnpm/hono@4.7.2/node_modules/hono/dist/compose.js:22:17)
ncore      |     at async contextStorage2 (file:///app/node_modules/.pnpm/hono@4.7.2/node_modules/hono/dist/middleware/context-storage/index.js:6:5)
ncore      |     at async dispatch (file:///app/node_modules/.pnpm/hono@4.7.2/node_modules/hono/dist/compose.js:22:17) {
ncore      |   [cause]: HeadersTimeoutError: Headers Timeout Error
ncore      |       at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:5975:32)
ncore      |       at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:2356:17)
ncore      |       at listOnTimeout (node:internal/timers:581:17)
ncore      |       at process.processTimers (node:internal/timers:519:7) {
ncore      |     code: 'UND_ERR_HEADERS_TIMEOUT'
ncore      |   }
ncore      | }

**Comment by hewdrey** [comment]
I am able to replicate it, if i click very fast randomly on the timeline on web.stremio.com.

**Comment by detarkende** [comment]
@bytecraft32 - I have fixed many issues in #59. Maybe your issue is also fixed with it (though I wasn't able to reproduce it on my Tizen OS tv so far). Could you please check version `0.9.0-pre-release`?

**Comment by bytecraft32** [comment]
@detarkende I checked with 0.9.0-pre-release, but the issue is still there.
Could you share your local mode settings, just to make sure mine are correct?

**Comment by Gusiee** [comment]
@detarkende first of all thank you so much for you effort to work on this brilliant addon! I'm using with local-only setup and I'm facing with the same issue like the others, seeking doesn't work for me as well on Tizen OS TVs. I have 3 Samsung TVs with different product years and categories, the issue is the same on all. Seeking works perfectly on Windows and Android devices but not on the TVs.

What I have noticed, if I open a stream and I try to seek for example to the middle, the seek immediately goes back to the current time where the stream was originally. BUT! If I close the stream, the "continue watching" shows that I'm in the middle with the stream but unfortunatelly if I try to coninue it, it starts the stream from it's beginning again.

I'm on 0.8.0 version.
